# Generated by Django 4.2 on 2023-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(verbose_name='DATE')),
                ('MinTemp', models.FloatField(verbose_name='MinTemp')),
                ('MaxTemp', models.FloatField(verbose_name='MaxTemp')),
                ('AvgTemp', models.FloatField(verbose_name='AvgTemp')),
                ('Total', models.BigIntegerField(verbose_name='Total')),
                ('Local', models.BigIntegerField(verbose_name='Local')),
                ('Exotic', models.BigIntegerField(verbose_name='Exotic')),
                ('EF', models.FloatField(verbose_name='EF')),
                ('Agric', models.BigIntegerField(verbose_name='Agric')),
            ],
        ),
    ]
